import type { Listing, Verein } from './supabase'

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    source: 'kleinanzeigen',
    title: 'Gemütlicher Kleingarten 280m² mit Laube in Prenzlauer Berg',
    price_abloese: 4500,
    size_sqm: 280,
    city: 'Berlin',
    plz: '10435',
    description: 'Schöner Kleingarten mit gepflegter 20m² Laube, Strom und Wasser vorhanden. Verein hat Warteliste geschlossen, Direktübernahme möglich mit Vereinszustimmung.',
    contact_url: 'https://www.kleinanzeigen.de',
    posted_at: '2026-05-10T00:00:00Z',
    scraped_at: '2026-05-14T00:00:00Z',
    active: true,
  },
  {
    id: '2',
    source: 'kleinanzeigen',
    title: 'Schrebergarten 320m² Handwerkerobjekt — günstig abzugeben',
    price_abloese: 800,
    size_sqm: 320,
    city: 'Berlin',
    plz: '13086',
    description: 'Renovierungsbedürftiger Garten mit alter Laube. Ideal für Handwerker. Jahresbeitrag ca. €350. Verein nimmt neue Mitglieder auf.',
    contact_url: 'https://www.kleinanzeigen.de',
    posted_at: '2026-05-08T00:00:00Z',
    scraped_at: '2026-05-14T00:00:00Z',
    active: true,
  },
  {
    id: '3',
    source: 'verein',
    title: 'Freie Parzelle 240m² — KGV Nordend München',
    price_abloese: 3200,
    size_sqm: 240,
    city: 'München',
    plz: '80809',
    description: 'Direkt vom Verein: gepflegte Parzelle mit Laube, Wasser und Stromanschluss. Bewerber müssen Vereinsmitglied werden.',
    contact_url: 'https://www.kgv-nordend.de',
    posted_at: '2026-05-01T00:00:00Z',
    scraped_at: '2026-05-14T00:00:00Z',
    active: true,
  },
]

export const MOCK_VEREINE: Verein[] = [
  {
    id: 'v1',
    name: 'KGV Am Volkspark Friedrichshain',
    address: 'Am Friedrichshain 1',
    city: 'Berlin',
    plz: '10249',
    bundesland: 'Berlin',
    website: 'https://example.de',
    warteliste_status: 'offen',
    warteliste_laenge: 45,
    parzellen_anzahl: 120,
    jahresbeitrag: 380,
    last_updated: '2026-04-01T00:00:00Z',
  },
  {
    id: 'v2',
    name: 'Kleingartenverein Prenzlauer Berg e.V.',
    address: 'Prenzlauer Allee 100',
    city: 'Berlin',
    plz: '10409',
    bundesland: 'Berlin',
    warteliste_status: 'geschlossen',
    warteliste_laenge: 210,
    parzellen_anzahl: 85,
    jahresbeitrag: 420,
    last_updated: '2026-03-15T00:00:00Z',
  },
  {
    id: 'v3',
    name: 'KGV Nordend München e.V.',
    address: 'Schleißheimer Str. 400',
    city: 'München',
    plz: '80809',
    bundesland: 'Bayern',
    website: 'https://kgv-nordend.de',
    warteliste_status: 'offen',
    warteliste_laenge: 30,
    parzellen_anzahl: 95,
    jahresbeitrag: 460,
    last_updated: '2026-05-01T00:00:00Z',
  },
  {
    id: 'v4',
    name: 'Gartenfreunde Hamburg-Eimsbüttel e.V.',
    address: 'Lutterothstr. 53',
    city: 'Hamburg',
    plz: '20255',
    bundesland: 'Hamburg',
    warteliste_status: 'unbekannt',
    parzellen_anzahl: 140,
    jahresbeitrag: 350,
    last_updated: '2025-12-01T00:00:00Z',
  },
]
